#!/bin/sh

TEMPLATECONF="$(pwd)/sources/meta-bootlink/confs/"
export TEMPLATECONF

BSPDIR="$(pwd)"
export BSPDIR

source sources/poky/oe-init-build-env $1

if [ -n "$DISTRO" ]
then
        sed -e "s,DISTRO ?= \"poky\",DISTRO ?= '$DISTRO',g" -i conf/local.conf
fi

echo "Copying local.conf and bblayers.conf"
cp -f ../sources/meta-bootlink/confs/local.conf.sample $1/conf/local.conf
cp -rf ../sources/meta-bootlink/confs/bblayers.conf.sample $1/conf/bblayers.conf
