#!/bin/sh

TEMPLATECONF="$(pwd)/sources/meta-bootlink/confs/"
export TEMPLATECONF

BSPDIR="$(pwd)"
export BSPDIR

source sources/poky/oe-init-build-env $1

if [ -n "$DISTRO" ]
then
        sed -e "s,DISTRO ?= \"poky\",DISTRO ?= '$DISTRO',g" -i conf/local.conf
fi

mv conf/local.conf conf/local.conf.sample
# Generate the local.conf based on the Yocto defaults
grep -v '^#\|^$' conf/local.conf.sample > conf/local.conf
